[package]
name = "telegram-decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "3.1.8", features = ["derive"] }

regex = "1"
derive_builder = "*"
serde = "*"

serde_json = "*"
serde_derive = "*"

g2poly = "0.4"

reqwest = { version = "0.11", features = ["json"] } # reqwest with JSON parsing support
futures = "0.3" # for our async / await blocks
tokio = { version = "1.15", features = ["full"] }

hex-string = "*"
